### ISSUE TITLE
[1.5.4-rc.1-phetio] State Wrapper doesn't copy solid solute

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/concentration#52]
Test Device: PC Laptop

OS: Windows 10 v. 1803

Browser: Google Chrome v. 67.0.3396.87

Problem Description: For phetsims/QA#128 when using the state wrapper the copied sim does not show any solid solute being mixed into the solution. The sim works fine otherwise. This is the same error that occurs on the concentration screen of the Beer's Law Lab as referenced in https://github.com/phetsims/beers-law-lab/issues/228.

Here is the error that appears in the console:
```

TypeError: Cannot read property 'constructor' of undefined
    at Object.getType (concentration_en-phetio.html?production:976)
    at Object.g [as setState] (concentration_en-phetio.html?production:976)
    at TPhETIO.implementation [as setState] (concentration_en-phetio.html?production:1005)
    at Object.invoke (concentration_en-phetio.html?production:1004)
    at Object.handleRequest (concentration_en-phetio.html?production:1004)
    at concentration_en-phetio.html?production:1004

```

**Comment by phet-steele** [comment]
> This is the same error that occurs on the concentration screen of the Beer's Law Lab as referenced in phetsims/beers-law-lab#228.

@JRomero0613 this is because the Concentration *sim* IS the same as the Concentration *screen* in Beer's Law Lab. They are literally the same thing. You will see almost no code [in this repo](https://github.com/phetsims/concentration/tree/master/js) because the code used to make this sim is the exact same code used in BLL. PhET does this often with their sims; sometimes it's straightforward like these two sims, other times it's a bit more tricky (like all the Area Model sims). Therefore, logging an issue in this repo is redundant. Simply mentioning in phetsims/beers-law-lab#228 that Concentration 1.5.4-rc.1 has this issue is sufficient.

Also, the `type:legacy-bug` is a label reserved for issues in legacy sims, ie. sims with a Java or Flash code base, not HTML5 sims.
